name: git2dart_binaries
description: Dart bindings and binaries libgit2 library
version: 0.0.7
repository: https://github.com/DartGit-dev/git2dart_bindings

environment:
  sdk: ">=2.19.2 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  ffi: ^2.0.0
  path: ^1.8.1
  pub_semver: ^2.1.3

dev_dependencies:
  ffigen: ^7.2.6
  lints: ^2.0.0
  test: ^1.21.0

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: Git2DartPlugin
